[build]
  base = "frontend/"
  command = "npm install && ls -l node_modules/.bin/tailwindcss && which tailwindcss && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://josereimondez-portfolio-backend.onrender.com/api/:splat"
  status = 200
