[build]
  base = "frontend/"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://josereimondez-portfolio-backend.onrender.com/api/:splat"
  status = 200
